{% set name = "pymeasure" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyMeasure-{{ version }}.tar.gz
  sha256: bb06ff13513ddb507bcde4c82440009599ba1ffe8cb970a39193cb6f4a8acbd8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - numpy >=1.6.1
    - pandas >=0.14
    - pyqtgraph >=0.9.10
    - pyserial >=2.7
    - pyvisa >=1.8

test:
  imports:
    - pymeasure
    - pymeasure.adapters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pymeasure/pymeasure
  license: MIT
  license_file: LICENSE.txt
  summary: Scientific measurement library for instruments, experiments, and live-plotting.
  description: |
    PyMeasure makes scientific measurements easy to set up and run. The package contains a 
    repository of instrument classes and a system for running experiment procedures, 
    which provides graphical interfaces for graphing live data and managing queues of 
    experiments. Both parts of the package are independent, and when combined provide 
    all the necessary requirements for advanced measurements with only limited coding.
  doc_url: http://pymeasure.readthedocs.io
  dev_url: https://github.com/pymeasure/pymeasure

extra:
  recipe-maintainers:
    - melund
    - ddale
    - cjermain
    - bilderbuchi
    - CasperSchippers
