travis:
  secure:
    BINSTAR_TOKEN: NLIm2u/CBUZOWI9v+3Qb3VGU3t02N43NXMCDfp7O3qAoV0gVMZ9MiQzIN33JZbAkXwsR7D9ElresDe3xsOFMJtVBYndcVTvOAMZkGZ8OmqxkAwDTJUpmF8OLhv9y8dOArZJ3R0YyW1iYfnwvIkjjBC9qLTt9/pLRGrCbSfsFmRaCBYMpaM7wCyWHDCbCAkxKL5K7Cg/JzhviErlcclt7Ps3iM9uj5MKXkOH4vYmZthi/B9RiZPC3Zoy1JR2vgSC03hlJxHfShTDuhQHte9NHfkg8WX23AAVBqIiFZvqBqZhhIveybMIkJYiK+cdWOJXDGoJB+kDcyupuW+U/xr+ePbw+lqWVUat7K0NZEnUbw01tL1oTQNaG8dTFIiPfzugSu5Ds8QkMLj/Kc702dMjfohHljLx/uJCxkX/gg2L7cPieetqwFCL/uy4paA5TjDZveH27h4mtZx0SMGEsj+011JpNkDA8FOsQ7F4L0QGE6XE6p679vgaOaCYQKmR2Tfx1SGRZCrJ76KPY4rO/6tKcrkZhXozkO9eEQUEB7qGK9WEFJPpdZyiiXHwJohBg3JrK4o9z4ndU0OrTFAAiAbQp5idihOL2sugSekyjaf5L6UvIg2GTlf46VroQI8qWuvtvntntN5csetOENWtT7mfKhS+5z6BxbrpEr3vfnSCtC5c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
