travis:
  secure:
    BINSTAR_TOKEN: EDPrLrYOFYI1UPQ8cmvYvuT+CTQwpeRFyOpyDEb+5AYmncmqo0jUb9PeJTpKM2kt5BEkMFtzjwwvFejfrLNAJxxxjxSEXI5edv9RJJD5zN7RtKkKmrL+MSl8+7Tdup+9drrcCqqDfWniqgH83zSdfnpuliBAP+BaTXWUkrqlr5/UeNkD4eva+9aWQoKO+T6rB70Wm3FcS2m8zqkHqB9MEzNuZcRxk1O8gU2/otV7YBfG5AN/4Cvd9nb0I/F8ZaIdkUZ3Mm36z5Gb7+QXSUVc1HlvIRPT86MnKNV24cgPpN4t2gaJOoQipT519itbfzqnacExpuPwI0CKQY7z4TweOTQiOvldfUpQm1j/RzkvcuctsgahOu+wql/oJQKrHgw6cUMArDrSL5rz/elDXKnwY89PYLUvMGoP/TJjEKBFq9vDUwseHXW6Xu/RkbQEeTBYYerb0jjEUh/SflHnWK9chmXl1ddc0uMrM0U7yD7n8ZiRxNz0Lw8ISZtgk3bIjm9oovjAHC+DI65/NkzpdIIpUU5iyiOf27GTa0RzyaU7DheK9X+nx/konLjgPSSKDiqJTFR8qsl0xWCQBWG5NcnLE5/9s5lKCsRMvITmzDwramwEuz+ZMFI1dkab9t+kyxh5p1w6tM3GOFVxpB3+tSH5z+A9GKMczoMAtLRx76c2xY4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
